### ISSUE TITLE
ocs:no schema for consolecontrol at 0 index!

### ISSUE THREAD

**Issue by ATFieldBeast** [cattyhouse/oc-guide#2]
请问在主板的logo之后会出现一段很快的“ocs:no schema for consolecontrol at 0 index!”，然后才开始引导并显示苹果的logo，是有什么地方配置地不对呢？
![IMG_3543](https://user-images.githubusercontent.com/22592396/71988320-a981ce00-326a-11ea-8321-17fcdbe2f867.png)
我已经把和console有关的选项都按sample.plist里的默认配置填好了还是会这样

**Comment by ATFieldBeast** [comment]
OK找到问题了

**Comment by lionoggo** [comment]
> OK找到问题了

怎么解决的
