### ISSUE TITLE
不知道为何机型从iMacPro1,1改成iMac19,1后，iStatsMenus读不到温度和风扇传感器

### ISSUE THREAD

**Issue by bjrjustin** [cattyhouse/oc-guide#3]

**Comment by cattyhouse** [comment]
iStatsMenus 只能读 FakeSMC 及其插件kext 所提供的信息, 因为这个软件对 FakeSMC 有特别的支持.  VirtualSMC的信息需要用 HWMonitorSMC2 读取.
