### ISSUE TITLE
SSDT-PLUG.aml 怎么修复？

### ISSUE THREAD

**Issue by bowencool** [cattyhouse/oc-guide#7]
安装遇到错误
![image](https://user-images.githubusercontent.com/20217146/84563320-29b5dd80-ad8d-11ea-878d-d5a8a4ae1809.png)

搜了一下，可能就是您提到的名称问题：

> SSDT-PLUG.aml 开启硬件变频功能, 作用于CPU, iGPU, dGPU. 注意此文件里面的 CPU 的位置和名称需要与 DSDT.aml 里面的一致, 可能的位置: _SB _PR 等, 可能的名称: PR00 CPU0 等, 不同的主板各不相同.

然后我也搜到了一个可能是正确答案的工具：[SSDTtime](https://github.com/corpnewt/SSDTTime)，但是这个工具我怎么操作都没反应。
所以来求助楼主

**Comment by bowencool** [comment]
我是按照官方推荐的配置：https://dortania.github.io/OpenCore-Desktop-Guide/config.plist/skylake.html#add
文件也是从这个地方下载的

**Comment by bowencool** [comment]
我把acpi全删了就好了。。

**Comment by cattyhouse** [comment]
我更新一下链接吧, OpenCore官方的那个dsl自动识别 cpu 名称, 直接可以用.

**Comment by cattyhouse** [comment]
SSDTtime 用于比较特殊的主板, 一般的主板不需要用它里面的SSDT

> 然后我也搜到了一个可能是正确答案的工具：[SSDTtime](https://github.com/corpnewt/SSDTTime)，但是这个工具我怎么操作都没反应。
> 所以来求助楼主

**Comment by bowencool** [comment]
> 我更新一下链接吧, OpenCore官方的那个dsl自动识别 cpu 名称, 直接可以用.

我就是用官方的才报的这个错，全删掉反而可以正常工作，不知道为啥

**Comment by cattyhouse** [comment]
看log, 显然你是用了其他的aml, 导致很多设备的 _STA 被删除了, _STA = status, 也就是SSDT表里面的设备的状态.
