### ISSUE TITLE
没权限下载

### ISSUE THREAD

**Issue by ryan628** [cattyhouse/oc-guide#8]
Access Denied
You don't have permission to access "http://oscdn.apple.com/content/downloads/59/10/001-43312/oifium3yx72dhc4po3r65zfwblslmce191/RecoveryImage/BaseSystem.chunklist" on this server.
Reference #18.7666d717.1608631983.11a385a8

**Comment by cattyhouse** [comment]
运行的什么下载命令

**Comment by ryan628** [comment]
我找到原因了 公司的网下载有限制,下载50M之后断网了2分钟 造成后续问题,用热点就可以了
